apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
      slot: green
  template:
    metadata:
      labels:
        app: python-app
        slot: green
    spec:
      containers:
      - name: python-app
        image: egxsmit/blue-green:GREEN_TAG
        ports:
        - containerPort: 5000
        env:
        - name: SLOT
          value: "green"
